// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// ルートレイアウト
import Layout from 'components/layout';

export default function RootLayout({ children }) {
 return (
    <html lang="ja">
      <body>
        <Layout>{ children }</Layout>
      </body>
    </html>
  )
}
